$(document).ready ->
  route = $('#map').data('url')
  mapping = new Mapping($('#map'), route)
  mapping.runMap()
  #mapping.addRoute()
  #mapping.addGeneralPoints()
  mapping.addBeachWalkwayPoints()
  mapping.addBeachWalkway()
  mapping.addLayerSwitcher()
  #mapping.addSelectionControls()
