default: &default
  adapter: postgis
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: walkways

test:
  <<: *default
  database: walkways_test

production:
  <<: *default
  database: walkways_production
  username: geo_demo
  password: <%= ENV['GEO_DEMO_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") %>
